version: '3.8'

services:
  backend:
    image: projet-infonuagique-backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/mydb
    networks:
      - app_network

  frontend:
    image: projet-infonuagique-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app_network

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_network
    ports:
      - "5432:5432"

networks:
  app_network:
    
volumes:
  db_data:
