version: '3.8'

services:
  backend:
    image: dockermariexmas/projet-infonuagique-backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/mydb
    networks:
      - app_network

  frontend:
    image: dockermariexmas/projet-infonuagique-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app_network

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_network
    ports:
      - "5432:5432"

  prometheus:
    image: prom/prometheus
    volumes:
      - ../../backend/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - app_network 
    
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - app_network
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    volumes:
      - grafana-storage:/var/lib/grafana

networks:
  app_network:
    
volumes:
  db_data:
  grafana-storage:
